apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-logistica-envios-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: logistica-envios-api
          image: franye/logisticaenvios:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: ConnectionStrings__LogisticaCS
              value: "Server=sqlserver-service,1433;Database=LogisticaEnviosDB;User Id=sa;Password=BigWhale123!;TrustServerCertificate=True;"