apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-logistica-envios-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: logistica-envios-api
        image: franye/logisticaenvios:dev
        ports:
        - containerPort: 80